import type { Metadata } from "next";
import { Miss_Fajardose } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const missFajardose = Miss_Fajardose({
  variable: "--font-miss-fajar-dose",
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl" className={`${missFajardose.variable} h-full antialiased `}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
